apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "event-pvc.name" . }}
spec:
  accessModes: 
    - {{ .Values.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hdfs-pvc.name" . }}
spec:
  accessModes:
    - {{ .Values.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.storageClass }}
---

